ignore_colors = [
 [0, 0, 0, 0],
 # [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed
# r/placeDE overlay target: https://place.army/overlay_target.png

[versions]
"browser" = 20
"python" = 3
"nodejs" = 1

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "bonjwa-logo29"
file = "bonjwa/Bonjwa_Logo_29x29.png"
startx = 282
starty = 134
priority = 10


[[structure]]
name = "bonjwa-matteo-marius"
file = "bonjwa/Matteo-Marius-reduced.png"
startx = 213
starty = 115
priority = 5

[[structure]]
name = "prinz"
file = "bonjwa/prinz.png"
startx = 166
starty = 134
priority = 1

[[structure]]
name = "bonjwa-peepo2"
file = "bonjwa/vorlage-peepo-1zu1.png"
startx = 189
starty = 132
priority = 1

[[structure]]
name = "HerzAlbanien"
file = "bonjwa/Herz.png"
startx = 198
starty = 154
priority = 1

[[structure]]
name = "HerzUK"
file = "bonjwa/Herz.png"
startx = 280
starty = 167
priority = 1

